name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-python@v7.0.0
        with:
          python-version: "3.13"
      - run: pip install pytest pytest-homeassistant-custom-component ruff
      - run: ruff check .
      - run: pytest
